# Generated by Django 3.2.9 on 2021-12-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('middle_name', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
                ('date_hired', models.DateField()),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('active', models.BooleanField()),
            ],
            bases=('persons.person',),
        ),
        migrations.CreateModel(
            name='Paystub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=7)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='persons.employee')),
            ],
        ),
    ]
