# Generated by Django 3.2.9 on 2021-11-23 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('middle_name', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
                ('id_number', models.IntegerField()),
                ('date_hired', models.DateField()),
                ('pay_rate', models.FloatField()),
                ('active', models.BooleanField()),
            ],
            bases=('persons.person',),
        ),
    ]
