# Generated by Django 3.2.9 on 2021-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paystub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('hours_worked', models.FloatField()),
                ('rate', models.FloatField()),
                ('gross_pay', models.IntegerField()),
                ('deductions', models.FloatField()),
                ('taxes', models.FloatField()),
                ('net_pay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_start', models.FloatField(default=0)),
                ('tue_start', models.FloatField(default=0)),
                ('wed_start', models.FloatField(default=0)),
                ('thu_start', models.FloatField(default=0)),
                ('fri_start', models.FloatField(default=0)),
                ('sat_start', models.FloatField(default=0)),
                ('sun_start', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_number',
        ),
        migrations.AddField(
            model_name='person',
            name='id_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
