# Generated by Django 3.2.9 on 2021-12-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20211123_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='fri_start',
            new_name='fri',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='mon_start',
            new_name='mon',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='sat_start',
            new_name='sat',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='sun_start',
            new_name='sun',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='thu_start',
            new_name='thu',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='tue_start',
            new_name='tue',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='wed_start',
            new_name='wed',
        ),
        migrations.RemoveField(
            model_name='paystub',
            name='deductions',
        ),
        migrations.AddField(
            model_name='paystub',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='persons.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='taxes',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
