# Generated by Django 3.2.9 on 2021-12-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20211130_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
